### ISSUE TITLE
Mesh.LookAt();

### ISSUE THREAD

**Issue by FinalEra** [kitzeller/multiplayer#1]
Funny bug where the player mesh stares at the ground if you click the ground under it.

https://photos.app.goo.gl/1YVFfT8s3iWYpNRRA

**Comment by kitzeller** [comment]
Temp-fix by setting z and x rotation to 0 after mesh.LookAt(); Will probably come up with a more elegant solution later!

**Comment by FinalEra** [comment]
Killin' it! :)
