### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by FinalEra** [kitzeller/multiplayer#2]
Has work on this been stopped? Hoping to see other player mesh rotation/animation soon :(

**Comment by kitzeller** [comment]
Just paused temporarily -- was finishing up a school project, which is now over so I can continue development! :)

**Comment by FinalEra** [comment]
Yay! :) I tried implementing this myself, and was going to send it upstream but I failed 😭. I was trying to change the Player constructor to handle both the current player and 'others' but it was doing wonky things like rotating/animating the current player when others moved. 😂😂

**Comment by kitzeller** [comment]
Hey @FinalEra - just so you know I've ported this project to another repo in order to create new features for a different type of game. I'm also happy to report it has other player mesh rotation/animation! https://github.com/kitzeller/medieval-clicker-game
